# --- {}
# api_id: 58****0
# api_hash: "87b2********************d9e"

proxy:
  enable: true
  scheme: http
  hostname: 127.0.0.1
  port: 11223

channel_id: -1001383316433
save_dir: ./downloads/
message_file: ./message_不绝对领域.txt
offset_id: 0
