# --- {}
# api_id: 58****0
# api_hash: "87b2********************d9e"

proxy:
  enable: true
  scheme: http
  hostname: 127.0.0.1
  port: 11223

channel_id: -1001383316433
save_dir: ./downloads/
# 请求消息的response保存文件
message_file: ./message_不绝对领域.txt
# 从哪条消息开始下载，0 表示从最早的消息开始下载
offset_id: 0  

# 分开存放文件时需要的配置
read_dir: ./downloads/
output_dir: ./output/
